# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

language: generic # optional, just removes the language badge

services:
  - docker

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# limit automatic builds to certain branches (and pull requests)
branches:
  only:
  - master

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - ROSDEP_SKIP_KEYS="log4cpp rtt ocl" # preinstalled in the docker images
    - AFTER_INIT_EMBED="source /opt/orocos/\${ROS_DISTRO}/setup.sh"
    - UPSTREAM_WORKSPACE="github:orocos/rtt_ros2_integration#master"
  matrix: # each line is a job
    - ROS_DISTRO="dashing" DOCKER_IMAGE="orocos/ros2-ci:dashing-ros-base-bionic"
    - ROS_DISTRO="eloquent" DOCKER_IMAGE="orocos/ros2-ci:eloquent-ros-base-bionic"
    - ROS_DISTRO="foxy" DOCKER_IMAGE="orocos/ros2-ci:foxy-ros-base-focal"

# allow failures, e.g. for unsupported distros
# matrix:
#   allow_failures:
#     - env: ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
